### ISSUE TITLE
Resize Image

### ISSUE THREAD

**Issue by BartoszSambor** [AGH-Narzedzia-Informatyczne/Project-Maze#14]
Nie działa ta komenda
pip install python-resize-image
Nie ma błędów, a biblioteki dalej nie znajduje.

**Comment by KubaKonieczny** [comment]
Sprawdź czy zainstalowało się w tym samym folderze co interpreter

**Comment by LukaszSuchan** [comment]
Prawdopodobnie zainstalowało się do folderu site-packages wiec musisz przenieś ten moduł do folderu Lib

**Comment by LukaszSuchan** [comment]
Prawdopodobnie zainstalowało się do folderu site-packages wiec musisz przenieś ten moduł do folderu Lib

**Comment by BartoszSambor** [comment]
Dzięki, przeniosłem tam gdzie inne biblioteki i działa, zamykam.
